const KEY='fangtracker-catches';let catches=[];try{catches=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){catches=[]}let coords=null,photoData='',editingId=null;
const $=id=>document.getElementById(id), species=['Hecht','Zander','Barsch','Aal','Karpfen','Schleie','Brasse','Rotauge','Forelle','Lachs','Wels','Dorsch','Makrele','Hering','Andere / eigene Fischart'];
function save(){localStorage.setItem(KEY,JSON.stringify(catches))} function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');render();scrollTo(0,0)}
function initSpecies(){species.forEach(s=>{let o=document.createElement('option');o.textContent=s;o.value=s;$('speciesSelect').appendChild(o)});$('speciesSelect').onchange=()=>$('customSpeciesWrap').classList.toggle('hidden',$('speciesSelect').value!=='Andere / eigene Fischart')}
function chosenSpecies(){return $('speciesSelect').value==='Andere / eigene Fischart'?$('customSpecies').value.trim():$('speciesSelect').value}
function newCatch(){editingId=null;resetForm();$('formTitle').textContent='Neuer Fang';$('saveBtn').textContent='Fang speichern';$('cancelEdit').classList.add('hidden');show('add')}
function resetForm(){$('form').reset();$('speciesSelect').value='Hecht';$('customSpeciesWrap').classList.add('hidden');coords=null;photoData='';$('preview').classList.add('hidden');$('preview').removeAttribute('src');$('photoStatus').textContent='Kein Foto ausgewählt';$('cameraInput').value='';$('libraryInput').value='';$('locText').textContent='Keine Position gespeichert';$('latInput').value='';$('lonInput').value=''}
function openCamera(){$('cameraInput').click()} function openLibrary(){$('libraryInput').click()}
function handlePhoto(e){const f=e.target.files&&e.target.files[0];if(!f)return;if(!f.type.startsWith('image/'))return alert('Bitte eine Bilddatei auswählen.');const r=new FileReader();r.onload=()=>{photoData=r.result;$('preview').src=photoData;$('preview').classList.remove('hidden');$('photoStatus').textContent='Foto ausgewählt ✓'};r.onerror=()=>alert('Das Foto konnte nicht gelesen werden.');r.readAsDataURL(f)}
function syncLocationFields(){if(coords){$('latInput').value=coords.lat.toFixed(6);$('lonInput').value=coords.lon.toFixed(6);$('locText').textContent=`Gespeichert: ${coords.lat.toFixed(5)}, ${coords.lon.toFixed(5)}`}else{$('latInput').value='';$('lonInput').value='';$('locText').textContent='Keine Position gespeichert'}}
function getLocation(){if(!navigator.geolocation)return $('locText').textContent='GPS nicht verfügbar';$('locText').textContent='Position wird ermittelt …';navigator.geolocation.getCurrentPosition(p=>{coords={lat:p.coords.latitude,lon:p.coords.longitude};syncLocationFields()},()=>{$('locText').textContent='Standortfreigabe nicht möglich'},{enableHighAccuracy:true,timeout:12000,maximumAge:0})}
function applyManualLocation(){const lat=parseFloat(String($('latInput').value).replace(',','.')),lon=parseFloat(String($('lonInput').value).replace(',','.'));if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat < -90||lat > 90||lon < -180||lon > 180)return alert('Bitte gültige Koordinaten eingeben. Breitengrad: -90 bis 90, Längengrad: -180 bis 180.');coords={lat,lon};syncLocationFields();alert('Fangposition wurde übernommen. Speichere anschließend den Fang.')}
function clearLocation(){coords=null;syncLocationFields()}
function openPositionMap(){let lat=parseFloat(String($('latInput').value).replace(',','.')),lon=parseFloat(String($('lonInput').value).replace(',','.'));if(!Number.isFinite(lat)||!Number.isFinite(lon)){if(coords){lat=coords.lat;lon=coords.lon}else return alert('Bitte zuerst GPS übernehmen oder Koordinaten eingeben.')}window.open(`https://maps.apple.com/?ll=${lat},${lon}&q=Fangposition`,'_blank')}

function editCatch(id){const c=catches.find(x=>x.id===id);if(!c)return;editingId=id;resetForm();if(species.includes(c.species)&&c.species!=='Andere / eigene Fischart')$('speciesSelect').value=c.species;else{$('speciesSelect').value='Andere / eigene Fischart';$('customSpeciesWrap').classList.remove('hidden');$('customSpecies').value=c.species}$('water').value=c.water||'';$('length').value=c.length||'';$('weight').value=c.weight||'';$('bait').value=c.bait||'';$('method').value=c.method||'';$('notes').value=c.notes||'';coords=c.coords||null;photoData=c.photo||'';if(photoData){$('preview').src=photoData;$('preview').classList.remove('hidden');$('photoStatus').textContent='Gespeichertes Foto'}if(coords)syncLocationFields();$('formTitle').textContent='Fang bearbeiten';$('saveBtn').textContent='Änderungen speichern';$('cancelEdit').classList.remove('hidden');show('add')}
function cancelEditing(){editingId=null;resetForm();show('log')}
$('form').onsubmit=e=>{e.preventDefault();const latRaw=$('latInput').value.trim(),lonRaw=$('lonInput').value.trim();if(latRaw||lonRaw){const lat=parseFloat(latRaw.replace(',','.')),lon=parseFloat(lonRaw.replace(',','.'));if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat < -90||lat > 90||lon < -180||lon > 180)return alert('Bitte gültige Positionsdaten eingeben.');coords={lat,lon}}let sp=chosenSpecies();if(!sp)return alert('Bitte eine Fischart eingeben.');const old=editingId?catches.find(x=>x.id===editingId):null;const data={id:editingId||Date.now(),date:old?.date||new Date().toISOString(),species:sp,water:$('water').value.trim(),length:+$('length').value||0,weight:+$('weight').value||0,bait:$('bait').value.trim(),method:$('method').value.trim(),notes:$('notes').value.trim(),coords,photo:photoData};if(editingId)catches=catches.map(x=>x.id===editingId?data:x);else catches.unshift(data);save();editingId=null;resetForm();show('home')};
function del(id){if(confirm('Diesen Fang wirklich löschen?')){catches=catches.filter(x=>x.id!==id);save();render()}}
function card(c){return `<div class='card'>${c.photo?`<img class='catch-photo' src='${c.photo}' onclick='viewPhoto(${c.id})'>`:`<div class='no-photo'>🐟</div>`}<div class='info'><b>${esc(c.species)}</b><div>${c.length?c.length+' cm':''}${c.length&&c.weight?' · ':''}${c.weight?c.weight+' kg':''}</div><div class='muted'>${esc(c.water||'Kein Gewässer')} · ${new Date(c.date).toLocaleDateString('de-DE')}</div>${c.bait?`<div class='muted'>Köder: ${esc(c.bait)}</div>`:''}<div class='card-actions'><button onclick='editCatch(${c.id})'>✏️ Bearbeiten</button><button class='danger' onclick='del(${c.id})'>🗑️</button></div></div></div>`}
function viewPhoto(id){const c=catches.find(x=>x.id===id);if(!c?.photo)return;const w=window.open();if(w)w.document.write(`<meta name='viewport' content='width=device-width'><body style='margin:0;background:#111;display:grid;place-items:center;min-height:100vh'><img src='${c.photo}' style='max-width:100%;max-height:100vh'></body>`)}
function renderList(){let q=($('search').value||'').toLowerCase();$('list').innerHTML=catches.filter(c=>[c.species,c.water,c.bait,c.method,c.notes].join(' ').toLowerCase().includes(q)).map(card).join('')||'<p>Noch keine Fänge gespeichert.</p>'}
function grouped(field){let m={};catches.forEach(c=>{let k=(c[field]||'').trim();if(k)m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function renderStats(){let maxL=Math.max(0,...catches.map(c=>c.length)),maxW=Math.max(0,...catches.map(c=>c.weight));let bySpecies=grouped('species'),byWater=grouped('water'),byBait=grouped('bait');let records=bySpecies.map(([s,n])=>{let a=catches.filter(c=>c.species===s),l=Math.max(0,...a.map(c=>c.length)),w=Math.max(0,...a.map(c=>c.weight));return `<div class='record'><b>${esc(s)}</b><div>${n} Fang${n===1?'':'e'}${l?' · '+l+' cm':''}${w?' · '+w+' kg':''}</div></div>`}).join('');$('statsBody').innerHTML=`<div class='stats'><div class='stat'><b>${catches.length}</b>Fänge</div><div class='stat'><b>${maxL||'–'}</b>cm</div><div class='stat'><b>${maxW||'–'}</b>kg</div></div><h2>Rekorde pro Fischart</h2>${records||'<p>Noch keine Daten.</p>'}<h2>Erfolgreichste Gewässer</h2>${topRows(byWater)}<h2>Erfolgreichste Köder</h2>${topRows(byBait)}`}
function topRows(a){return a.slice(0,8).map(([k,n])=>`<div class='rank'><span>${esc(k)}</span><b>${n}</b></div>`).join('')||'<p class="muted">Noch keine Daten.</p>'}
function render(){let maxL=Math.max(0,...catches.map(c=>c.length)),maxW=Math.max(0,...catches.map(c=>c.weight));$('summary').innerHTML=`<div class='stat'><b>${catches.length}</b>Fänge</div><div class='stat'><b>${maxL||'–'}</b>cm Rekord</div><div class='stat'><b>${maxW||'–'}</b>kg Rekord</div>`;$('recent').innerHTML=catches.slice(0,3).map(card).join('')||'<p>Noch keine Fänge. Trag deinen ersten Fang ein.</p>';renderList();renderStats();let geo=catches.filter(c=>c.coords);$('mapList').innerHTML=geo.map(c=>`<div class='map-card'>${c.photo?`<img src='${c.photo}'>`:''}<div><b>${esc(c.species)}</b><div>${esc(c.water||'Ohne Gewässername')}</div><div class='muted'>${new Date(c.date).toLocaleDateString('de-DE')} · ${c.coords.lat.toFixed(5)}, ${c.coords.lon.toFixed(5)}</div><a target='_blank' rel='noopener' href='https://maps.apple.com/?ll=${c.coords.lat},${c.coords.lon}&q=${encodeURIComponent(c.species+' '+(c.water||'Fangplatz'))}'>📍 Karte öffnen</a></div></div>`).join('')||'<p>Noch keine Fangpositionen gespeichert.</p>'}
function exportBackup(){const blob=new Blob([JSON.stringify({app:'FangTracker',version:'1.3',exported:new Date().toISOString(),catches},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`FangTracker-Backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('importInput').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result),arr=Array.isArray(d)?d:d.catches;if(!Array.isArray(arr))throw 0;if(confirm(`Backup mit ${arr.length} Fängen wiederherstellen? Die aktuellen Daten werden ersetzt.`)){catches=arr;save();render();alert('Backup wurde wiederhergestellt.')}}catch(x){alert('Diese Datei ist kein gültiges FangTracker-Backup.')}e.target.value=''};r.readAsText(f)};
$('search').oninput=renderList;$('cameraInput').addEventListener('change',handlePhoto);$('libraryInput').addEventListener('change',handlePhoto);initSpecies();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
