let catches=JSON.parse(localStorage.getItem('fangtracker-catches')||'[]');let coords=null,photoData='';
const $=id=>document.getElementById(id);function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');render()}
function openCamera(){$('cameraInput').click()} function openLibrary(){$('libraryInput').click()}
function handlePhoto(e){const f=e.target.files&&e.target.files[0];if(!f)return;if(!f.type.startsWith('image/')){alert('Bitte eine Bilddatei auswählen.');return}const r=new FileReader();r.onload=()=>{photoData=r.result;$('preview').src=photoData;$('preview').classList.remove('hidden');$('photoStatus').textContent='Foto ausgewählt ✓'};r.onerror=()=>alert('Das Foto konnte nicht gelesen werden.');r.readAsDataURL(f)}
$('cameraInput').addEventListener('change',handlePhoto);$('libraryInput').addEventListener('change',handlePhoto);
function getLocation(){if(!navigator.geolocation)return $('locText').textContent='GPS nicht verfügbar';$('locText').textContent='Position wird ermittelt …';navigator.geolocation.getCurrentPosition(p=>{coords={lat:p.coords.latitude,lon:p.coords.longitude};$('locText').textContent=`${coords.lat.toFixed(5)}, ${coords.lon.toFixed(5)}`},()=>{$('locText').textContent='Standortfreigabe nicht möglich'})}
$('form').onsubmit=e=>{e.preventDefault();catches.unshift({id:Date.now(),date:new Date().toISOString(),species:$('species').value,water:$('water').value,length:+$('length').value||0,weight:+$('weight').value||0,bait:$('bait').value,method:$('method').value,notes:$('notes').value,coords,photo:photoData});localStorage.setItem('fangtracker-catches',JSON.stringify(catches));e.target.reset();coords=null;photoData='';$('preview').classList.add('hidden');$('preview').removeAttribute('src');$('photoStatus').textContent='Kein Foto ausgewählt';$('cameraInput').value='';$('libraryInput').value='';$('locText').textContent='Keine Position gespeichert';show('home')};
$('search').oninput=()=>renderList();
function card(c){return `<div class='card'>${c.photo?`<img src='${c.photo}'>`:`<img alt=''>`}<div class='info'><b>${esc(c.species)}</b><div>${c.length?c.length+' cm · ':''}${c.weight?c.weight+' kg':''}</div><div class='muted'>${esc(c.water||'Kein Gewässer')} · ${new Date(c.date).toLocaleDateString('de-DE')}</div><div class='muted'>${esc(c.bait||'')}</div></div><button onclick='del(${c.id})'>✕</button></div>`}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function del(id){if(confirm('Diesen Fang löschen?')){catches=catches.filter(x=>x.id!==id);localStorage.setItem('fangtracker-catches',JSON.stringify(catches));render()}}
function renderList(){let q=($('search').value||'').toLowerCase();$('list').innerHTML=catches.filter(c=>[c.species,c.water,c.bait,c.method].join(' ').toLowerCase().includes(q)).map(card).join('')||'<p>Noch keine Fänge gespeichert.</p>'}
function render(){let maxL=Math.max(0,...catches.map(c=>c.length)),maxW=Math.max(0,...catches.map(c=>c.weight));$('summary').innerHTML=`<div class='stat'><b>${catches.length}</b>Fänge</div><div class='stat'><b>${maxL||'–'}</b>cm Rekord</div><div class='stat'><b>${maxW||'–'}</b>kg Rekord</div>`;$('recent').innerHTML=catches.slice(0,3).map(card).join('')||'<p>Noch keine Fänge. Trag deinen ersten Fang ein.</p>';renderList();let counts={};catches.forEach(c=>counts[c.species]=(counts[c.species]||0)+1);let top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];$('statsBody').innerHTML=`<div class='record'><b>Gesamt</b><div>${catches.length} Fänge</div></div><div class='record'><b>Längster Fisch</b><div>${maxL?maxL+' cm':'–'}</div></div><div class='record'><b>Schwerster Fisch</b><div>${maxW?maxW+' kg':'–'}</div></div><div class='record'><b>Häufigste Fischart</b><div>${top?esc(top[0])+' ('+top[1]+')':'–'}</div></div>`;let geo=catches.filter(c=>c.coords);$('mapList').innerHTML=geo.map(c=>`<div class='record'><b>${esc(c.species)}</b><div>${esc(c.water)}</div><a target='_blank' rel='noopener' href='https://maps.apple.com/?ll=${c.coords.lat},${c.coords.lon}'>Position in Karten öffnen</a></div>`).join('')||'<p>Noch keine Fangpositionen gespeichert.</p>'}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
